<?php

namespace AppBundle\Repository;

/**
 * SalonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalonRepository extends \Doctrine\ORM\EntityRepository
{
}
