app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation
salons:
    type: rest
    resource: AppBundle\Controller\SalonController
users:
    type:     rest
    resource: AppBundle\Controller\UserController